
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.additem_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.add_it())
        self.additem_pushButton.setGeometry(QtCore.QRect(30, 120, 81, 31))
        self.additem_pushButton.setObjectName("additem_pushButton")
        self.deleteitem_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.deleteitem_pushButton_2.setGeometry(QtCore.QRect(150, 120, 81, 31))
        self.deleteitem_pushButton_2.setObjectName("deleteitem_pushButton_2")
        self.clearall_pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.clearall_pushButton_3.setGeometry(QtCore.QRect(280, 120, 81, 31))
        self.clearall_pushButton_3.setObjectName("clearall_pushButton_3")
        self.additem_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.additem_lineEdit.setGeometry(QtCore.QRect(32, 19, 331, 71))
        self.additem_lineEdit.setObjectName("additem_lineEdit")
        self.show_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.show_listWidget.setGeometry(QtCore.QRect(30, 160, 331, 231))
        self.show_listWidget.setObjectName("show_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionConfigaration = QtWidgets.QAction(MainWindow)
        self.actionConfigaration.setObjectName("actionConfigaration")
        self.actionAdd_New_2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fugue-icons-3.5.6/icons/plus-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_New_2.setIcon(icon)
        self.actionAdd_New_2.setObjectName("actionAdd_New_2")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("fugue-icons-3.5.6/icons/document-sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("fugue-icons-3.5.6/icons/document-share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionConfigaration_2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("fugue-icons-3.5.6/icons/hammer-screwdriver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigaration_2.setIcon(icon3)
        self.actionConfigaration_2.setObjectName("actionConfigaration_2")
        self.actionVersion_2 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("fugue-icons-3.5.6/icons/paper-plane--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion_2.setIcon(icon4)
        self.actionVersion_2.setObjectName("actionVersion_2")
        self.menuFile.addAction(self.actionAdd_New_2)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuSetting.addAction(self.actionConfigaration_2)
        self.menuAbout.addAction(self.actionVersion_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.additem_pushButton.setText(_translate("MainWindow", "Add Item"))
        self.deleteitem_pushButton_2.setText(_translate("MainWindow", "Delete"))
        self.clearall_pushButton_3.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionConfigaration.setText(_translate("MainWindow", "Configaration"))
        self.actionAdd_New_2.setText(_translate("MainWindow", "Add New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionConfigaration_2.setText(_translate("MainWindow", "Configaration"))
        self.actionVersion_2.setText(_translate("MainWindow", "Version"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
