# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Laptop\RajIT Project\attendence app\Python App\input.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(414, 203)
        InputWindow.setStyleSheet("background-color: rgb(81, 81, 81)")
        self.centralwidget = QtWidgets.QWidget(InputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 21, 16))
        self.label.setObjectName("label")
        self.Ip_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Ip_lineEdit.setGeometry(QtCore.QRect(60, 20, 321, 20))
        self.Ip_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Ip_lineEdit.setObjectName("Ip_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 31, 16))
        self.label_2.setObjectName("label_2")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Port_lineEdit.setGeometry(QtCore.QRect(60, 50, 321, 20))
        self.Port_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 31, 16))
        self.label_3.setObjectName("label_3")
        self.Api_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Api_lineEdit.setGeometry(QtCore.QRect(60, 80, 321, 20))
        self.Api_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Api_lineEdit.setObjectName("Api_lineEdit")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(310, 110, 75, 31))
        self.saveButton.setStyleSheet("background-color: rgb(144, 144, 144)")
        self.saveButton.setObjectName("saveButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_4.setObjectName("label_4")
        InputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        InputWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InputWindow)
        self.statusbar.setObjectName("statusbar")
        InputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        _translate = QtCore.QCoreApplication.translate
        InputWindow.setWindowTitle(_translate("InputWindow", "Input Your IP"))
        self.label.setText(_translate("InputWindow", "IP"))
        self.label_2.setText(_translate("InputWindow", "Port"))
        self.label_3.setText(_translate("InputWindow", "API"))
        self.saveButton.setText(_translate("InputWindow", "Save"))
        self.label_4.setText(_translate("InputWindow", "Powerd By rajIT Ltd."))
