# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Laptop\RajIT Project\attendence app\Python App\input.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(414, 203)
        InputWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(InputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ip_label = QtWidgets.QLabel(self.centralwidget)
        self.ip_label.setGeometry(QtCore.QRect(30, 40, 21, 16))
        self.ip_label.setObjectName("ip_label")
        self.Ip_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Ip_lineEdit.setGeometry(QtCore.QRect(60, 40, 321, 20))
        self.Ip_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Ip_lineEdit.setInputMask("")
        self.Ip_lineEdit.setText("")
        self.Ip_lineEdit.setObjectName("Ip_lineEdit")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setGeometry(QtCore.QRect(30, 70, 31, 16))
        self.port_label.setObjectName("port_label")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Port_lineEdit.setGeometry(QtCore.QRect(60, 70, 321, 20))
        self.Port_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Port_lineEdit.setText("")
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(230, 110, 75, 31))
        self.saveButton.setStyleSheet("")
        self.saveButton.setObjectName("saveButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 121, 16))
        self.label_4.setObjectName("label_4")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(310, 110, 75, 31))
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        InputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        InputWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InputWindow)
        self.statusbar.setObjectName("statusbar")
        InputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        _translate = QtCore.QCoreApplication.translate
        InputWindow.setWindowTitle(_translate("InputWindow", "Add New Device"))
        self.ip_label.setText(_translate("InputWindow", "IP"))
        self.port_label.setText(_translate("InputWindow", "Port"))
        self.saveButton.setText(_translate("InputWindow", "Save"))
        self.label_4.setText(_translate("InputWindow", "Powerd By rajIT Ltd."))
        self.okButton.setText(_translate("InputWindow", "Ok"))
